refine

diff --git a/Dockerfile.python3 b/Dockerfile.python3
--- a/Dockerfile.python3
+++ b/Dockerfile.python3
@@ -13,22 +13,27 @@ ENV PYTHON_GET_PIP_SHA256=96461deced5c2a487ddc65207ec5a9cffeca0d34e7af7ea1afc470
 
 RUN /bin/sh -c set -eux; \
   apt-get update; \
-  savedAptMark="$(apt-mark showmanual)"; \
+  $(apt-mark showmanual) > /savedAptMark ; \
   apt-get install -y --no-install-recommends ca-certificates netbase tzdata dpkg-dev gcc gnupg libbluetooth-dev libbz2-dev libc6-dev libdb-dev libexpat1-dev libffi-dev libgdbm-dev liblzma-dev libncursesw5-dev libreadline-dev libsqlite3-dev libssl-dev make tk-dev uuid-dev wget xz-utils zlib1g-dev libjpeg-dev libfreetype6-dev ; \
   wget -O python.tar.xz "https://www.python.org/ftp/python/${PYTHON_VERSION%%[a-z]*}/Python-$PYTHON_VERSION.tar.xz"; \
   wget -O python.tar.xz.asc "https://www.python.org/ftp/python/${PYTHON_VERSION%%[a-z]*}/Python-$PYTHON_VERSION.tar.xz.asc"; \
+  wget -O get-pip.py "$PYTHON_GET_PIP_URL"; \
   GNUPGHOME="$(mktemp -d)"; \
   export GNUPGHOME; \
   gpg --batch --keyserver hkps://keys.openpgp.org --recv-keys "$GPG_KEY"; \
   gpg --batch --verify python.tar.xz.asc python.tar.xz; \
   gpgconf --kill all; \
   rm -rf "$GNUPGHOME" python.tar.xz.asc; \
+  echo "$PYTHON_GET_PIP_SHA256 *get-pip.py" | sha256sum -c -; \
   mkdir -p /usr/src/python; \
   tar --extract --directory /usr/src/python --strip-components=1 --file python.tar.xz; \
-  rm python.tar.xz; \
+  rm python.tar.xz
+
+# install python
+RUN /bin/sh -c set -eux; \
   cd /usr/src/python; \ 
     gnuArch="$(dpkg-architecture --query DEB_BUILD_GNU_TYPE)"; \
-    ./configure --build="$gnuArch" --enable-loadable-sqlite-extensions --enable-optimizations --enable-option-checking=fatal --enable-shared --with-system-expat --without-ensurepip ; \
+    ./configure --build="$gnuArch" --enable-loadable-sqlite-extensions --enable-optimizations --with-lto --enable-option-checking=fatal --enable-shared --with-system-expat --without-ensurepip ; \
     nproc="$(nproc)"; \
     EXTRA_CFLAGS="$(dpkg-buildflags --get CFLAGS)"; \
     LDFLAGS="$(dpkg-buildflags --get LDFLAGS)"; \
@@ -39,43 +44,39 @@ RUN /bin/sh -c set -eux; \
     make install; \
   cd /; \
   rm -rf /usr/src/python; \
-  find /usr/local -depth \( \( -type d -a \( -name test -o -name tests -o -name idle_test \) \) -o \( -type f -a \( -name '*.pyc' -o -name '*.pyo' -o -name 'libpython*.a' \) \) \) -exec rm -rf '{}' + ; \
-  ldconfig; \
-  apt-mark auto '.*' > /dev/null; \
-  apt-mark manual $savedAptMark; \
-  find /usr/local -type f -executable -not \( -name '*tkinter*' \) -exec ldd '{}' ';' | awk '/=>/ { print $(NF-1) }' | sort -u | xargs -r dpkg-query --search | cut -d: -f1 | sort -u | xargs -r apt-mark manual ; \
-  apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false; \
-  rm -rf /var/lib/apt/lists/*; \
-  python3 --version
-
-RUN \
   for src in idle3 pydoc3 python3 python3-config; do \
     dst="$(echo "$src" | tr -d 3)"; \
     [ -s "/usr/local/bin/$src" ]; \
     [ ! -e "/usr/local/bin/$dst" ]; \ 
     ln -svT "$src" "/usr/local/bin/$dst"; \
-  done
+  done; \
+  python3 --version
 
-RUN \
-  savedAptMark="$(apt-mark showmanual)"; \
-  wget -O get-pip.py "$PYTHON_GET_PIP_URL"; \
-  echo "$PYTHON_GET_PIP_SHA256 *get-pip.py" | sha256sum -c -; \
-  apt-mark auto '.*' > /dev/null; \
-  [ -z "$savedAptMark" ] || apt-mark manual $savedAptMark > /dev/null; \
-  apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false; \
-  rm -rf /var/lib/apt/lists/*; \
+# install pip
+RUN /bin/sh -c set -eux; \
   export PYTHONDONTWRITEBYTECODE=1; \
   python get-pip.py --disable-pip-version-check --no-cache-dir --no-compile "pip==$PYTHON_PIP_VERSION" "setuptools==$PYTHON_SETUPTOOLS_VERSION" ; \
   rm -f get-pip.py; \
   pip --version
 
-#RUN apt install build-essential -y
+# cleanup
+RUN /bin/sh -c set -eux; \
+  find /usr/local -depth \( \( -type d -a \( -name test -o -name tests -o -name idle_test \) \) -o \( -type f -a \( -name '*.pyc' -o -name '*.pyo' -o -name 'libpython*.a' \) \) \) -exec rm -rf '{}' + ; \
+  ldconfig; \
+  apt-mark auto '.*' > /dev/null; \
+  apt-mark manual $(cat /savedAptMark); \
+  find /usr/local -type f -executable -not \( -name '*tkinter*' \) -exec ldd '{}' ';' | awk '/=>/ { print $(NF-1) }' | sort -u | xargs -r dpkg-query --search | cut -d: -f1 | sort -u | xargs -r apt-mark manual ; \
+  apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false; \
+  apt-get clean; \
+  apt-get autoclean; \
+  rm -rf /var/cache/apt/archives/* /var/lib/apt/lists/*
+
 # Build numpy as a wheel
-RUN python -m pip wheel --wheel-dir=/root/wheels numpy 
+RUN python -m pip wheel --wheel-dir=/root/wheels numpy
 # Build pillow as a wheel
-RUN python -m pip wheel --wheel-dir=/root/wheels  'pillow<9.0.0,>=8.0.0' 
+RUN python -m pip wheel --wheel-dir=/root/wheels 'pillow<9.0.0,>=8.0.0'
 # actfw requires pillow<9.0.0,>=8.0.0
 RUN python -m pip install --no-index --find-links=/root/wheels numpy pillow
 
-#CMD ["python3"]
+CMD ["bash"]
 
